# This is based on the NumPy AppVeyor config for multibuild.  Thanks, NumPy
# maintainers!

environment:
  global:
      OPENBLAS_32: "https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/openblas-v0.3.7-win32-gcc_7_1_0.zip"
      OPENBLAS_64: "https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/openblas-v0.3.7-win_amd64-gcc_7_1_0.zip"
      ARMADILLO_SRC: "https://sourceforge.net/projects/arma/files/armadillo-9.800.3.tar.xz"
      BOOST_PROG_OPTION : "C:/projects/mlpack-wheels/boost_program_options-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
      BOOST_MATH : "C:/projects/mlpack-wheels/boost_math_c99-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
      BOOST_RANDOM : "C:/projects/mlpack-wheels/boost_random-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
      BOOST_SERIALIZATION : "C:/projects/mlpack-wheels/boost_serialization-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
      BOOST_UNIT_TEST : "C:/projects/mlpack-wheels/boost_unit_test_framework-vc140.1.60.0.0/lib/native/address-model-64/lib/*.*"
      CYTHON_BUILD_DEP: Cython
      TEST_MODE: fast
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
      APPVEYOR_SKIP_FINALIZE_ON_EXIT: true
      WHEELHOUSE_UPLOADER_USERNAME: travis-worker
      WHEELHOUSE_UPLOADER_SECRET:
        secure:
            9s0gdDGnNnTt7hvyNpn0/ZzOMGPdwPp2SewFTfGzYk7uI+rdAN9rFq2D1gAP4NQh
      BUILD_COMMIT: 3.2.2
      BLAS_LIBRARY : "%APPVEYOR_BUILD_FOLDER%/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a"

  matrix:
#    - PYTHON: C:/Python36
#      PYTHON_VERSION: 3.6
#      PYTHON_ARCH: 32

    - PYTHON: C:/Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

#    - PYTHON: C:/Python37
#      PYTHON_VERSION: 3.7
#      PYTHON_ARCH: 32

#    - PYTHON: C:/Python37-x64
#      PYTHON_VERSION: 3.7
#      PYTHON_ARCH: 64

#    - PYTHON: C:/Python38
#      PYTHON_VERSION: 3.8
#      PYTHON_ARCH: 32

#    - PYTHON: C:/Python38-x64
#      PYTHON_VERSION: 3.8
#      PYTHON_ARCH: 64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""
  # TODO: I bet this can be removed because we only build for releases
  - ps: >-
      if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
        $env:CONTAINER = "pre-release"
        if ($env:DAILY_COMMIT) { $env:BUILD_COMMIT = $env:DAILY_COMMIT }
      } else {
        $env:CONTAINER = "wheels"
        $env:UPLOAD_ARGS = "--no-update-index"
      }

install:
  - cmd: echo "Filesystem root:"
  - dir C:\

  - echo "Installed SDKs:"
  - dir "C:/Program Files/Microsoft SDKs/Windows"

  # Get needed submodules
  - git submodule update --init

  # Install new Python if necessary
  - ps: ./multibuild/install_python.ps1

  # Prepend required Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - >-
     python -c "import sys,platform,struct;
     print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"
  # Download and install static "openblas.a" to PYTHON/lib
  - ps: |
      $PYTHON_ARCH = $env:PYTHON_ARCH
      $PYTHON = $env:PYTHON
      If ($PYTHON_ARCH -eq 32) {
          $OPENBLAS = $env:OPENBLAS_32
      } Else {
          $OPENBLAS = $env:OPENBLAS_64
      }
      $clnt = new-object System.Net.WebClient
      $file = "$(New-TemporaryFile).zip"
      $tmpdir = New-TemporaryFile | %{ rm $_; mkdir $_ }
      $destination = "$PYTHON/lib/openblas.a"
      echo $file
      echo $tmpdir
      echo $OPENBLAS
      $clnt.DownloadFile($OPENBLAS,$file)
      Expand-Archive $file $tmpdir
      rm $tmpdir/$PYTHON_ARCH/lib/*.dll.a
      $lib = ls $tmpdir/$PYTHON_ARCH/lib/*.a | ForEach { ls $_ } | Select-Object -first 1
      echo $lib
      cp $lib $destination
      ls $destination
  # Upgrade to the latest pip, setuptools, and wheel.
  - python -m pip install -U pip setuptools wheel

  # Install build requirements.
  - pip install "%CYTHON_BUILD_DEP%" --install-option="--no-cython-compile"
  - pip install numpy pandas

  # Download boost for Visual Studio.
  - ps: nuget install boost -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.60.0
  - ps: >
      nuget install boost_unit_test_framework-vc140
      -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.60.0
  - ps: >
      nuget install boost_program_options-vc140
      -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.60.0
  - ps: >
      nuget install boost_random-vc140
      -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.60.0
  - ps: >
      nuget install boost_serialization-vc140
      -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.60.0
  - ps: >
      nuget install boost_math_c99-vc140
      -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.60.0

  - ps: nuget install OpenBLAS -o "${env:APPVEYOR_BUILD_FOLDER}"

  - mkdir boost_libs
  - ps: cp ${env:BOOST_PROG_OPTION} boost_libs\
  - ps: cp ${env:BOOST_MATH} boost_libs\
  - ps: cp ${env:BOOST_RANDOM} boost_libs\
  - ps: cp ${env:BOOST_SERIALIZATION} boost_libs\
  - ps: cp ${env:BOOST_UNIT_TEST} boost_libs\
  - cd boost_libs
  - dir
  - pwd
  - cd ..


build_script:
  # Build Armadillo.
  - >
    appveyor DownloadFile %ARMADILLO_SRC%
    -FileName armadillo.tar.xz
  - 7z x armadillo.tar.xz -so -txz | 7z x -si -ttar > nul
  - cd armadillo-9.800.3
  - mkdir build
  - cd build
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - >
    cmake
    -DBLAS_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DLAPACK_LIBRARY:FILEPATH=%BLAS_LIBRARY%
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_SHARED_LIBS=OFF
    -G "Visual Studio 14 2015 Win64"
    ..
  - >
    MSBuild armadillo.sln /m /verbosity:quiet
    /p:Configuration=Release
  - cd Release
  - dir
  - cd ..
  - copy Release/armadillo.lib "%PYTHON%/lib/"
  - cd ../..

  # Finally build mlpack.
  - cd mlpack
  - git checkout %BUILD_COMMIT%
  - mkdir build
  - cd build
  - >
    cmake
    -DDEBUG=OFF
    -DPROFILE=OFF
    -DBUILD_PYTHON_BINDINGS=ON
    -DBUILD_CLI_EXECUTABLES=OFF
    -DBUILD_TESTS=OFF
    -DBUILD_SHARED_LIBS=OFF
    -DPYTHON_EXECUTABLE=%PYTHON%/python.exe
    -DARMADILLO_INCLUDE_DIR=../../armadillo-9.800.3/include/
    -DARMADILLO_LIBRARY=%PYTHON%/lib/armadillo.lib
    -DBOOST_INCLUDEDIR=%APPVEYOR_BUILD_FOLDER%/boost.1.60.0.0/lib/native/include/
    -DBOOST_LIBRARYDIR=%APPVEYOR_BUILD_FOLDER%/boost_libs/
    -DLAPACK_LIBRARY=%BLAS_LIBRARY%
    -DBLAS_LIBRARY=%BLAS_LIBRARY%
    -DBOOST_ROOT=../boost_1_60_0/
    -DUSE_OPENMP=OFF
    -G "Visual Studio 14 2015 Win64"
    ../
  - >
    MSBuild mlpack.sln
    /m /verbosity:minimal /nologo /p:BuildInParallel=true
    /p:Configuration=Release

  - cd src/mlpack/bindings/python/
  - python setup.py bdist_wheel

