env:
  global:
    - BUILD_COMMIT=3.4.1
    - BUILD_DEPENDS="Cython numpy pandas"
    - TEST_DEPENDS="Cython numpy pandas" # Not sure, but probably ok.
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - WHEELHOUSE_UPLOADER_USERNAME=mlpack-travis-worker
    - BUILD_DIR=/io/mlpack/build/src/mlpack/bindings/python/
    - secure: "k0mPQqseoLGpzDT03iMVw8m6noOKALGoZRLW4GKSeG4N4Jbx6YKP7VXpnbEixf0dbB8QzDoEWgmFbAhe16S7fSD5Oqn6edo+TouE9//691pQbzbxguaaGByibjjTweIWYvBBxQP/fCPFfegFnMaRI2HxzSbiBornN2PzpUT76pvKXKzT3UqP1ZGD0Fg3fhWOGcawJZA5HVUG+lKnmfBMUIfu/+u7SsYggEsEgq0be3PoxUuyz3tCBh++jntjN0jFLA5nO2+Y2O/fYdPoA0XHcXpQoWZg4v+NLwEMPFkolEWbFG0JXNlQktDOXrq/fXN6Z5KY2rfGC71PmqlAsgGIEasvCsFiZycuUNcwmVltHeOWZv0+EJBXXHIx9IbE/8XrzB89BYUGEquAbpTNjJJ4hzgId0nwVaCSU74SH6tJGU41gZsWVXUsiiy1oMBqrrQ/CWZWYeWfIPVgRCyX2O5faD/Kc3tvO7oCPuOEKgggJcA3FCu7itqXkT7p3dfGAixASH0LBizmEoAYISb6PY1UcTjOWo4XDSudbbwnrLMzt0UuO4zqa6h2yXnfShjE9p63ATqNy3OrWKz8H68nnJGV1bUyKpqWyJ1P1IakibaIwuCCn74fcmlfccKOYyt/ByS2hQyZtsYJWFJOr1IdKjLTAxEiWlMLUko1TxRH3Sp0UJ0="

language: generic
dist: xenial
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PATCH=0

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PATCH=1

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PATCH=0

    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PATCH=1

    # Don't upload mlpack3 for python 3.8, just mlpack.
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PATCH=0

    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
        - MB_PYTHON_OSX_VER=10.9
        - BUILD_DIR=/Users/travis/build/mlpack/mlpack-wheels/mlpack/build/src/mlpack/bindings/python/
        - PATCH=0

    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
        - MB_PYTHON_OSX_VER=10.9
        - BUILD_DIR=/Users/travis/build/mlpack/mlpack-wheels/mlpack/build/src/mlpack/bindings/python/
        - PATCH=1

    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_PYTHON_OSX_VER=10.9
        - BUILD_DIR=/Users/travis/build/mlpack/mlpack-wheels/mlpack/build/src/mlpack/bindings/python/
        - PATCH=0

    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_PYTHON_OSX_VER=10.9
        - BUILD_DIR=/Users/travis/build/mlpack/mlpack-wheels/mlpack/build/src/mlpack/bindings/python/
        - PATCH=1

    # Don't upload mlpack3 for python 3.8, just mlpack.
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8
        - MB_PYTHON_OSX_VER=10.9
        - BUILD_DIR=/Users/travis/build/mlpack/mlpack-wheels/mlpack/build/src/mlpack/bindings/python/
        - PATCH=0

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - clean_code mlpack $BUILD_COMMIT
  - echo "export PATCH=$PATCH" > mlpack/patch-info.sh
  - sed -i 's/${PACKAGE_VERSION}/${PACKAGE_VERSION}.post1/' mlpack/src/mlpack/bindings/python/setup.py.in
  - cat mlpack/src/mlpack/bindings/python/setup.py.in
  - build_wheel $BUILD_DIR $PLAT
  - pip install --upgrade twine
  - twine upload --verbose -u mlpack-travis-worker -p "$PYPI_PASSWORD" --skip-existing ~/build/mlpack/mlpack-wheels/wheelhouse/mlpack*

script:
  - cd ~/build/mlpack/mlpack-wheels/
  - install_run $PLAT

after_success:
  - echo "hooray!!"
