jobs:
- job: linux
  strategy:
    matrix:
      # I literally cannot believe that Azure Pipelines does not support
      # multiple axis builds.
      cp36-manylinux_x86_64:
        CIBW_BUILD: cp36-manylinux_x86_64
        BUILD_SCRIPT: build_mlpack.sh
        NUM_CORES: 4
      cp37-manylinux_x86_64:
        CIBW_BUILD: cp37-manylinux_x86_64
        BUILD_SCRIPT: build_mlpack.sh
        NUM_CORES: 4
      cp38-manylinux_x86_64:
        CIBW_BUILD: cp38-manylinux_x86_64
        BUILD_SCRIPT: build_mlpack.sh
        NUM_CORES: 4
      cp39-manylinux_x86_64:
        CIBW_BUILD: cp39-manylinux_x86_64
        BUILD_SCRIPT: build_mlpack.sh
        NUM_CORES: 4
      cp310-manylinux_x86_64:
        CIBW_BUILD: cp310-manylinux_x86_64
        BUILD_SCRIPT: build_mlpack.sh
        NUM_CORES: 4
      cp311-manylinux_x86_64:
        CIBW_BUILD: cp311-manylinux_x86_64
        BUILD_SCRIPT: build_mlpack.sh
        NUM_CORES: 4
      pp37-manylinux_x86_64:
        CIBW_BUILD: pp37-manylinux_x86_64
        BUILD_SCRIPT: build_mlpack.sh
        NUM_CORES: 4
      pp38_manylinux_x86_64:
        CIBW_BUILD: pp38-manylinux_x86_64
        BUILD_SCRIPT: build_mlpack.sh
        NUM_CORES: 4
      pp39_manylinux_x86_64:
        CIBW_BUILD: pp39-manylinux_x86_64
        BUILD_SCRIPT: build_mlpack.sh
        NUM_CORES: 4

      cp36-manylinux_i686:
        CIBW_BUILD: cp36-manylinux_i686
        BUILD_SCRIPT: build_mlpack.i686.sh
        NUM_CORES: 4
      cp37-manylinux_i686:
        CIBW_BUILD: cp37-manylinux_i686
        BUILD_SCRIPT: build_mlpack.i686.sh
        NUM_CORES: 4
      cp38-manylinux_i686:
        CIBW_BUILD: cp38-manylinux_i686
        BUILD_SCRIPT: build_mlpack.i686.sh
        NUM_CORES: 4
      cp39-manylinux_i686:
        CIBW_BUILD: cp39-manylinux_i686
        BUILD_SCRIPT: build_mlpack.i686.sh
        NUM_CORES: 4
      cp310-manylinux_i686:
        CIBW_BUILD: cp310-manylinux_i686
        BUILD_SCRIPT: build_mlpack.i686.sh
        NUM_CORES: 4
      cp311-manylinux_i686:
        CIBW_BUILD: cp311-manylinux_i686
        BUILD_SCRIPT: build_mlpack.i686.sh
        NUM_CORES: 4
      pp37-manylinux_i686:
        CIBW_BUILD: pp37-manylinux_i686
        BUILD_SCRIPT: build_mlpack.i686.sh
        NUM_CORES: 4
      pp38_manylinux_i686:
        CIBW_BUILD: pp38-manylinux_i686
        BUILD_SCRIPT: build_mlpack.i686.sh
        NUM_CORES: 4
      pp39_manylinux_i686:
        CIBW_BUILD: pp39-manylinux_i686
        BUILD_SCRIPT: build_mlpack.i686.sh
        NUM_CORES: 4

      cp36-musllinux_x86_64:
        CIBW_BUILD: cp36-musllinux_x86_64
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp37-musllinux_x86_64:
        CIBW_BUILD: cp37-musllinux_x86_64
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp38-musllinux_x86_64:
        CIBW_BUILD: cp38-musllinux_x86_64
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp39-musllinux_x86_64:
        CIBW_BUILD: cp39-musllinux_x86_64
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp310-musllinux_x86_64:
        CIBW_BUILD: cp310-musllinux_x86_64
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp311-musllinux_x86_64:
        CIBW_BUILD: cp311-musllinux_x86_64
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1

      cp36-musllinux_i686:
        CIBW_BUILD: cp36-musllinux_i686
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp37-musllinux_i686:
        CIBW_BUILD: cp37-musllinux_i686
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp38-musllinux_i686:
        CIBW_BUILD: cp38-musllinux_i686
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp39-musllinux_i686:
        CIBW_BUILD: cp39-musllinux_i686
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp310-musllinux_i686:
        CIBW_BUILD: cp310-musllinux_i686
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1
      cp311-musllinux_i686:
        CIBW_BUILD: cp311-musllinux_i686
        BUILD_SCRIPT: build_mlpack.musl.sh
        NUM_CORES: 1

  timeoutInMinutes: 0 # No limit for build time.
  pool: {vmImage: 'Ubuntu-20.04'}
  variables:
    MLPACK_VERSION: 4.0.0
    CIBW_TEST_COMMAND: python -c 'import mlpack; import numpy as np; x = np.random.rand(100, 10); o = mlpack.pca(input_=x, new_dimensionality=5, verbose=True)'
    # The PYPI_TOKEN variable is automatically set by Azure Pipelines.
    TWINE_PYPI_TOKEN: $(PYPI_TOKEN)
  steps:
    - template: azure-pipelines-linux-steps.yml

- job: macos
  strategy:
    matrix:
      cp36-macosx_x86_64:
        CIBW_BUILD: cp36-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp37-macosx_x86_64:
        CIBW_BUILD: cp37-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp38-macosx_x86_64:
        CIBW_BUILD: cp38-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp38-macosx_arm64:
        CIBW_BUILD: cp38-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"
      cp39-macosx_x86_64:
        CIBW_BUILD: cp39-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp39-macosx_arm64:
        CIBW_BUILD: cp39-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"
      cp310-macosx_x86_64:
        CIBW_BUILD: cp310-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp310-macosx_arm64:
        CIBW_BUILD: cp310-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"
      cp311-macosx_x86_64:
        CIBW_BUILD: cp311-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp311-macosx_arm64:
        CIBW_BUILD: cp311-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"
      pp38-macosx_x86_64:
        CIBW_BUILD: pp38-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      pp39-macosx_x86_64:
        CIBW_BUILD: pp39-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"

  timeoutInMinutes: 0 # No limit for build time.
  pool: {vmImage: 'macOS-11'}
  variables:
    MLPACK_VERSION: 4.0.0
    CIBW_TEST_COMMAND: python -c 'import mlpack; import numpy as np; x = np.random.rand(100, 10); o = mlpack.pca(input_=x, new_dimensionality=5, verbose=True)'
    # The PYPI_TOKEN variable is automatically set by Azure Pipelines.
    TWINE_PYPI_TOKEN: $(PYPI_TOKEN)
  steps:
    - template: azure-pipelines-macos-steps.yml

- job: windows
  strategy:
    matrix:
      cp36-win_amd64:
        CIBW_BUILD: cp36-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp36-win32:
        CIBW_BUILD: cp36-win32
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "Win32"
        OPENBLAS_ARCH: "x86"
      cp37-win_amd64:
        CIBW_BUILD: cp37-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp37-win32:
        CIBW_BUILD: cp37-win32
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "Win32"
        OPENBLAS_ARCH: "x86"
      cp38-win_amd64:
        CIBW_BUILD: cp38-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp38-win32:
        CIBW_BUILD: cp38-win32
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "Win32"
        OPENBLAS_ARCH: "x86"
      cp39-win_amd64:
        CIBW_BUILD: cp39-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp39-win32:
        CIBW_BUILD: cp39-win32
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "Win32"
        OPENBLAS_ARCH: "x86"
      cp310-win_amd64:
        CIBW_BUILD: cp310-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp310-win32:
        CIBW_BUILD: cp310-win32
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "Win32"
        OPENBLAS_ARCH: "x86"
      cp311-win_amd64:
        CIBW_BUILD: cp311-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp311-win32:
        CIBW_BUILD: cp311-win32
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "Win32"
        OPENBLAS_ARCH: "x86"
      pp38-win_amd64:
        CIBW_BUILD: pp38-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      pp39-win_amd64:
        CIBW_BUILD: pp39-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"

  timeoutInMinutes: 0 # No limit for build time.
  pool: {vmImage: 'windows-2019'}
  variables:
    MLPACK_VERSION: 4.0.0
    # The PYPI_TOKEN variable is automatically set by Azure Pipelines.
    TWINE_PYPI_TOKEN: $(PYPI_TOKEN)
  steps:
    - template: azure-pipelines-windows-steps.yml
