jobs:
- job: macos
  strategy:
    matrix:
      cp38-macosx_x86_64:
        CIBW_BUILD: cp38-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp38-macosx_arm64:
        CIBW_BUILD: cp38-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"
      cp39-macosx_x86_64:
        CIBW_BUILD: cp39-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp39-macosx_arm64:
        CIBW_BUILD: cp39-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"
      cp310-macosx_x86_64:
        CIBW_BUILD: cp310-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp310-macosx_arm64:
        CIBW_BUILD: cp310-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"
      cp311-macosx_x86_64:
        CIBW_BUILD: cp311-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp311-macosx_arm64:
        CIBW_BUILD: cp311-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"
      cp312-macosx_x86_64:
        CIBW_BUILD: cp312-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp312-macosx_arm64:
        CIBW_BUILD: cp312-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"
      cp313-macosx_x86_64:
        CIBW_BUILD: cp313-macosx_x86_64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "x86_64"
      cp313-macosx_arm64:
        CIBW_BUILD: cp313-macosx_arm64
        BUILD_SCRIPT: build_mlpack.osx.sh
        CIBW_ARCHS_MACOS: "arm64"

  timeoutInMinutes: 0 # No limit for build time.
  pool: {vmImage: 'macOS-14'}
  variables:
    MLPACK_VERSION: 4.6.2
    CIBW_TEST_COMMAND: python -c 'import mlpack; import numpy as np; x = np.random.rand(100, 10); o = mlpack.pca(input_=x, new_dimensionality=5, verbose=True)'
    # The PYPI_TOKEN variable is automatically set by Azure Pipelines.
    TWINE_PYPI_TOKEN: $(PYPI_TOKEN)
  steps:
    - template: azure-pipelines-macos-steps.yml

- job: windows
  strategy:
    matrix:
      cp38-win_amd64:
        CIBW_BUILD: cp38-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp39-win_amd64:
        CIBW_BUILD: cp39-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp310-win_amd64:
        CIBW_BUILD: cp310-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp311-win_amd64:
        CIBW_BUILD: cp311-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp312-win_amd64:
        CIBW_BUILD: cp312-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      cp313-win_amd64:
        CIBW_BUILD: cp313-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      pp38-win_amd64:
        CIBW_BUILD: pp38-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"
      pp39-win_amd64:
        CIBW_BUILD: pp39-win_amd64
        BUILD_SCRIPT: build_mlpack.bat
        WIN_ARCH: "x64"
        OPENBLAS_ARCH: "x64"

  timeoutInMinutes: 0 # No limit for build time.
  pool: {vmImage: 'windows-2019'}
  variables:
    MLPACK_VERSION: 4.6.2
    # The PYPI_TOKEN variable is automatically set by Azure Pipelines.
    TWINE_PYPI_TOKEN: $(PYPI_TOKEN)
  steps:
    - template: azure-pipelines-windows-steps.yml
