steps:
  - task: UsePythonVersion@0
  - bash: |
      set -o errexit
      python3 -m pip install --upgrade pip
      pip3 install cibuildwheel cython numpy pandas setuptools twine
      brew install --force armadillo cereal gcc cmake ensmallen
    displayName: Install dependencies

  - bash: |
      git clone https://github.com/mlpack/mlpack
      cd mlpack
      git checkout $(MLPACK_VERSION)
    displayName: Clone mlpack

  - bash: |
      mkdir -p mlpack/build
      cd mlpack/build
      cmake -DBUILD_PYTHON_BINDINGS=ON ../
      make python_configured
    displayName: Generate setup.py

  - bash: |
      brew uninstall --force armadillo cereal ensmallen arpack hdf5 open-mpi openblas r superlu cmake gcc
    displayName: Remove dependencies before entering build environment

  - bash: |
      export CIBW_BEFORE_BUILD="./$(BUILD_SCRIPT)"
      cibuildwheel --output-dir wheelhouse mlpack/build/src/mlpack/bindings/python/
    displayName: Build wheels

  - task: PublishBuildArtifacts@1
    inputs: {pathtoPublish: 'wheelhouse'}

  - bash: |
      echo "[pypi]" > ~/.pypirc
      echo "username = __token__" >> ~/.pypirc
      echo "password = $(TWINE_PYPI_TOKEN)" >> ~/.pypirc
      twine upload wheelhouse/*.whl
      rm -f ~/.pypirc
    displayName: Push wheels to PyPI
