jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-20.04'}
  variables:
    MLPACK_VERSION: 4.0.0
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel cython numpy pandas setuptools
        sudo apt-get update
        sudo apt-get install libarmadillo-dev libcereal-dev g++ cmake libensmallen-dev
      displayName: Install dependencies

    - bash: |
        git clone https://github.com/mlpack/mlpack
        cd mlpack
        git checkout $(MLPACK_VERSION)
      displayName: Clone mlpack

    - bash: |
        mkdir -p mlpack/build
        cd mlpack/build
        cmake -DBUILD_PYTHON_BINDINGS=ON ../
        make python_configured
      displayName: Generate setup.py

    - bash: |
        export CIBW_BEFORE_ALL="pwd && ls && $PWD/build_mlpack.sh"
        cibuildwheel --output-dir wheelhouse mlpack/build/src/mlpack/bindings/python/
      displayName: Build wheels

    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
