jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-20.04'}
  variables:
    CIBW_BEFORE_BUILD: "./build_mlpack.sh"
    MLPACK_VERSION: 4.0.0
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel
      displayName: Install dependencies

    - bash: |
        git clone https://github.com/mlpack/mlpack
        cd mlpack
        git checkout $(MLPACK_VERSION)
        cd ..
      displayName: Clone mlpack

    - bash: |
        cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels

    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
