name: Build aarch64, s390x, and ppc64le wheels

on: [push]

env:
  MLPACK_COMMIT: 4.0.0
  CIBW_TEST_COMMAND: python -c 'import mlpack; import numpy as np; x = np.random.rand(100, 10); o = mlpack.pca(input_=x, new_dimensionality=5, verbose=True)'

jobs:
  linux_build_wheels:
    name: Build wheel for ${{ matrix.py_ver }}-${{ matrix.host }}_${{ matrix.arch }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
#        py_ver: [cp36, cp37, cp38, cp39, cp310, cp311, pp37, pp38, pp39]
        py_ver: [cp311]
        # numpy does not build for s390x: "error: 'HWCAP_S390_VX' undeclared".
        arch: [aarch64, ppc64le]
        host: [manylinux, musllinux]
        exclude:
          - py_ver: pp37
            arch: s390x
          - py_ver: pp38
            arch: s390x
          - py_ver: pp39
            arch: s390x
          - py_ver: pp37
            arch: ppc64le
          - py_ver: pp38
            arch: ppc64le
          - py_ver: pp39
            arch: ppc64le
          - py_ver: pp37
            host: musllinux
          - py_ver: pp38
            host: musllinux
          - py_ver: pp39
            host: musllinux

    env:
      CIBW_BUILD: ${{ matrix.py_ver }}-${{ matrix.host }}_${{ matrix.arch }}
      CIBW_BEFORE_BUILD: "${{ matrix.host == 'manylinux' && './build_mlpack.emulated.sh' || './build_mlpack.musl.sh' }}"

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Install dependencies
        run: |
          sudo apt-get install libopenblas-dev libarmadillo-dev libensmallen-dev libcereal-dev g++ cmake
          sudo pip install numpy cython pandas

      - name: Generate setup.py
        run: |
          git clone https://github.com/mlpack/mlpack
          cd mlpack/
          git checkout $MLPACK_COMMIT
          mkdir build/
          cd build/
          cmake -DBUILD_PYTHON_BINDINGS=ON ../
          make python_configured

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.11.2
        with:
          package-dir: mlpack/build/src/mlpack/bindings/python/
        env:
          CIBW_ARCHS_LINUX: "${{ matrix.arch }}"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  windows_arm_build_wheels:
    name: Build wheel for ${{ matrix.py_ver }}-win_arm64
    runs-on: windows-latest
    strategy:
      matrix:
        py_ver: [cp311]

    env:
      CIBW_BUILD: ${{ matrix.py_ver }}-win_arm64

    steps:
      - uses: actions/checkout@v3

      - name: "Set up Visual Studio"
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '16'

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          # I guess this will go out of date...
          vcpkgGitCommitId: 'bdf073a835ebea07e1d039cd9cff4f650014e4ce'

      - name: Install OpenBLAS via vcpkg
        run: vcpkg install openblas:arm64-windows

      - name: Download Armadillo
        shell: bash
        run: |
          curl -O -L https://files.mlpack.org/armadillo-11.4.1.tar.gz
          tar -xvzf armadillo-11.4.1.tar.gz

      - name: Configure and build Armadillo
        shell: powershell
        run: |
          $rootdir = $pwd
          cd armadillo-11.4.1/
          cmake -G "Visual Studio 17 2022" `
              -DBLAS_LIBRARY:FILEPATH="C:\vcpkg\packages\openblas_arm64-windows\lib\openblas.lib" `
              -DLAPACK_LIBRARY:FILEPATH="C:\vcpkg\packages\openblas_arm64-windows\lib\openblas.lib" `
              -DBUILD_SHARED_LIBS=OFF `
              -DCMAKE_BUILD_TYPE=Release .
          cmake --build . --target armadillo --config Release

      - name: Download ensmallen
        shell: bash
        run: |
          curl -O -L https://www.ensmallen.org/files/ensmallen-2.19.0.tar.gz
          tar -xvzf ensmallen-2.19.0.tar.gz
          # No build needed---it's header-only.

      - name: Download cereal
        shell: bash
        run: |
          curl -O -L https://github.com/USCILab/cereal/archive/refs/tags/v1.3.2.tar.gz
          tar -xvzf v1.3.2.tar.gz

      - name: Clone mlpack
        shell: bash
        run: |
          git clone https://github.com/mlpack/mlpack
          cd mlpack
          git checkout $MLPACK_VERSION

      - name: Generate setup.py
        shell: powershell
        run: |
          $rootdir = $pwd
          cd mlpack
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" `
              -DBLAS_LIBRARIES:FILEPATH="C:\vcpkg\packages\openblas_arm64-windows\lib\openblas.lib" `
              -DLAPACK_LIBRARIES:FILEPATH="C:\vcpkg\packages\openblas_arm64-windows\lib\openblas.lib" `
              -DARMADILLO_INCLUDE_DIR="$rootdir\armadillo-11.4.1\tmp\include" `
              -DARMADILLO_LIBRARY="$rootdir\armadillo-11.4.1\Release\armadillo.lib" `
              -DCEREAL_INCLUDE_DIR="$rootdir\cereal-1.3.2\include" `
              -DENSMALLEN_INCLUDE_DIR="$rootdir\ensmallen-2.19.0\include\" `
              -DBUILD_JULIA_BINDINGS=OFF `
              -DBUILD_PYTHON_BINDINGS=ON `
              -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --target python_configured --config Release

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.11.2
        with:
          package-dir: mlpack/build/src/mlpack/bindings/python/
        env:
          CIBW_ARCHS_WINDOWS: "ARM64"
          CIBW_BEFORE_BUILD: "build_mlpack.bat"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:/vcpkg/packages/openblas_arm64-windows/bin/ -w {dest_dir} {wheel}"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
